// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231108104356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Data.Entities.ContactEntity", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Birth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("ContactId");

                    b.ToTable("contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Birth = new DateTime(2023, 11, 8, 11, 43, 56, 389, DateTimeKind.Local).AddTicks(4409),
                            Email = "adam@wsei.edu.pl",
                            Name = "Adam",
                            Phone = "123456789"
                        },
                        new
                        {
                            ContactId = 2,
                            Birth = new DateTime(2023, 11, 8, 11, 43, 56, 389, DateTimeKind.Local).AddTicks(4456),
                            Email = "ewa@wsei.edu.pl",
                            Name = "Ewa",
                            Phone = "123456777"
                        },
                        new
                        {
                            ContactId = 3,
                            Birth = new DateTime(2023, 11, 8, 11, 43, 56, 389, DateTimeKind.Local).AddTicks(4460),
                            Email = "karol@wsei.edu.pl",
                            Name = "Karol",
                            Phone = "123456788"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
